<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRAWMCMG\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRAWMCMG/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRAWMCMG.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRAWMCMG\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRAWMCMG\App_KernelProdContainer([
    'container.build_hash' => 'RAWMCMG',
    'container.build_id' => '835bb80a',
    'container.build_time' => 1591733184,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRAWMCMG');
