<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vente extends \App\Entity\Vente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'totalVente', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'dateVente', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'venteProduits', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'typePaiement', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'montantVerse', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'montantRendu', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'totalVente', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'dateVente', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'venteProduits', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'typePaiement', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'montantVerse', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'montantRendu', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Vente' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalVente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalVente', []);

        return parent::getTotalVente();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalVente(string $totalVente): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalVente', [$totalVente]);

        return parent::setTotalVente($totalVente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixNetPayer(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixNetPayer', []);

        return parent::getPrixNetPayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixNetPayer(string $prixNetPayer): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixNetPayer', [$prixNetPayer]);

        return parent::setPrixNetPayer($prixNetPayer);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateVente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateVente', []);

        return parent::getDateVente();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateVente(string $dateVente): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateVente', [$dateVente]);

        return parent::setDateVente($dateVente);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient(): ?\App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(?\App\Entity\Client $client): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getVenteProduits(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVenteProduits', []);

        return parent::getVenteProduits();
    }

    /**
     * {@inheritDoc}
     */
    public function addVenteProduit(\App\Entity\VenteProduit $venteProduit): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVenteProduit', [$venteProduit]);

        return parent::addVenteProduit($venteProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVenteProduit(\App\Entity\VenteProduit $venteProduit): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVenteProduit', [$venteProduit]);

        return parent::removeVenteProduit($venteProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypePaiement(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypePaiement', []);

        return parent::getTypePaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypePaiement(?string $typePaiement): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypePaiement', [$typePaiement]);

        return parent::setTypePaiement($typePaiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantVerse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantVerse', []);

        return parent::getMontantVerse();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantVerse(?string $montantVerse): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantVerse', [$montantVerse]);

        return parent::setMontantVerse($montantVerse);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantRendu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantRendu', []);

        return parent::getMontantRendu();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantRendu(string $montantRendu): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantRendu', [$montantRendu]);

        return parent::setMontantRendu($montantRendu);
    }

    /**
     * {@inheritDoc}
     */
    public function createdAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createdAt', []);

        return parent::createdAt();
    }

    /**
     * {@inheritDoc}
     */
    public function updateAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateAt', []);

        return parent::updateAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): \App\Entity\Vente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

}
