<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY5Mxfeb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY5Mxfeb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY5Mxfeb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY5Mxfeb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY5Mxfeb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y5Mxfeb',
    'container.build_id' => 'e5297d35',
    'container.build_time' => 1594061245,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY5Mxfeb');
