<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerApS35ls\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerApS35ls/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerApS35ls.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerApS35ls\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerApS35ls\App_KernelDevDebugContainer([
    'container.build_hash' => 'ApS35ls',
    'container.build_id' => 'e1af2a72',
    'container.build_time' => 1593986260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerApS35ls');
