<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.518d4a5c.js',
                '/build/0.9dbea6ed.js',
                '/build/app.f5357b01.js',
            ],
            'css' => [
                '/build/0.e6599092.css',
                '/build/app.f3ca0635.css',
            ],
        ],
    ],
],

]];
