<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.518d4a5c.js',
                '/build/0.766273aa.js',
                '/build/app.0a8da961.js',
            ],
            'css' => [
                '/build/0.3af5e433.css',
                '/build/app.eb6c0e7c.css',
            ],
        ],
    ],
],

]];
