<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Depot extends \App\Entity\Depot implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'stockInitial', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'quantiteDeposee', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'EnStock', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'quantiteVendue', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'quantiteRestantee', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'produit', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'stockInitial', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'quantiteDeposee', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'EnStock', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'quantiteVendue', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'quantiteRestantee', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'produit', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Depot' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Depot $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getStockInitial(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockInitial', []);

        return parent::getStockInitial();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockInitial(int $stockInitial): \App\Entity\Depot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockInitial', [$stockInitial]);

        return parent::setStockInitial($stockInitial);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantiteDeposee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantiteDeposee', []);

        return parent::getQuantiteDeposee();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantiteDeposee(int $quantiteDeposee): \App\Entity\Depot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantiteDeposee', [$quantiteDeposee]);

        return parent::setQuantiteDeposee($quantiteDeposee);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnStock', []);

        return parent::getEnStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnStock(int $EnStock): \App\Entity\Depot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnStock', [$EnStock]);

        return parent::setEnStock($EnStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantiteVendue(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantiteVendue', []);

        return parent::getQuantiteVendue();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantiteVendue(int $quantiteVendue): \App\Entity\Depot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantiteVendue', [$quantiteVendue]);

        return parent::setQuantiteVendue($quantiteVendue);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantiteRestantee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantiteRestantee', []);

        return parent::getQuantiteRestantee();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantiteRestantee(int $quantiteRestantee): \App\Entity\Depot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantiteRestantee', [$quantiteRestantee]);

        return parent::setQuantiteRestantee($quantiteRestantee);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduit(): ?\App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduit', []);

        return parent::getProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduit(?\App\Entity\Produit $produit): \App\Entity\Depot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduit', [$produit]);

        return parent::setProduit($produit);
    }

    /**
     * {@inheritDoc}
     */
    public function createdAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createdAt', []);

        return parent::createdAt();
    }

    /**
     * {@inheritDoc}
     */
    public function updateAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateAt', []);

        return parent::updateAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Depot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): \App\Entity\Depot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

}
